name: UnitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php-version }}
          configuration: tests/phpunit.xml